format_version: 10
pipelines:
  ParameterStoreDetroy:
    group: defaultGroup
    label_template: "${COUNT}"
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/raki009/aws-ssm-parameters
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Apply:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: ["init"]

                - exec:
                    command: terraform
                    arguments: ["destroy", "-auto-approve"]